### ISSUE TITLE
How to get request body with httpcontext?

### ISSUE THREAD

**Issue by majidbigdeli** [max-ieremenko/ServiceModel.Grpc#102]
Hi 
Thank you for this amazing project.
I want get parameter from request body in middleware
With httpcontext but i can not get request body

**Comment by max-ieremenko** [comment]
Parsing request body is not a trivial task, please check [server filters](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/ServerFilters) instead

**Comment by majidbigdeli** [comment]
Thank you for reply.
Yes, I know I can use server filter or grpc interceptor but I wanted to use middleware
because my grpc services are soap services.
I use [ServiceModel.Grpc](https://github.com/max-ieremenko/ServiceModel.Grpc)  and [SoapCore](https://github.com/DigDes/SoapCore) together with the same services
So I am looking for the same solution work in the two library

**Comment by max-ieremenko** [comment]
Here is [HTTP/1.1 JSON gateway for Swagger UI](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/master/Sources/ServiceModel.Grpc.AspNetCore/Internal/Swagger/SwaggerUiMiddleware.cs): handles http/1.1 request, emulates http/2 gRPC request and converts gRPC response to http/1.1 response. Maybe it can help.

**Comment by majidbigdeli** [comment]
Thank you
yes yes ISwaggerUiRequestHandler is ok .
