### ISSUE TITLE
Question: Best serialisation method for performance

### ISSUE THREAD

**Issue by lefig** [max-ieremenko/ServiceModel.Grpc#137]
Hi Max

A great project and sincerely thank you for it.

In your opinion is grpc-dotnet serialisation most likely to out perform other methods?

I read that Protobuf is highly regarded for speed but your benchmark results don't seem to reflect this.

Thanks.

Fig

**Comment by max-ieremenko** [comment]
Hi lefig.

The "grpc-dotnet" and "ServiceModelGrpc.proto-emulation" benchmarks demonstrate that Google.Protobuf is a winner.
Google.Protobuf is highly performant and it is expected - no reflection, only generated code.

About others, you see numbers.

Tests transfer this [SomeObject](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/master/Benchmarks/ServiceModel.Grpc.Benchmarks/Domain/SomeObject.cs). You can try other structures, closer to your domain area, it may slightly change the numbers, also there are other tests in [Benchmarks.sln](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Benchmarks):

``` bash
> ServiceModel.Grpc.Benchmarks.exe --filter *Marshaller*
```

Here are more [benchmarks](https://github.com/neuecc/MessagePack-CSharp#messagepack-for-c-net-net-core-unity-xamarin).

**Comment by lefig** [comment]
Hi Max,

Thank you for coming back with your thoughts. 

Also the docmentation and examples that you provide are very educational.

Coming from a WCF Duplex background I am still trying to find the best approach for GRPC. 

Best,
Fig

**Comment by max-ieremenko** [comment]
Hi lefig,

I close this issue. It would be interesting if you could share "WCF Duplex background" in another issue.
