### ISSUE TITLE
 Multiple Implementations of a Service Contract on Same Server

### ISSUE THREAD

**Issue by srdhruv** [max-ieremenko/ServiceModel.Grpc#143]
**Is your feature request related to a problem? Please describe.**
Problem:

Server cannot register multiple service classes implementing a common service contract interface on the same machine and same port.

Example:
```csharp
[ServiceContract()] 
public interface IBootService
{
	...
	//Some operation contracts
	...
}

[ServiceContract()] 
public interface IDataFetchService
{
	...
	//Some operation contracts
	...
}

[ServiceContract()] 
public interface IDataStorageService
{
	...
	//Some operation contracts
	...
}

public DataFetchService: IBootService, IDataFetchService
{
	...
}

public DataStorageService: IBootService, IDataStorageService
{
	...
}
```
We currently have lot of WCF services running and all of them implements IBootService. IBootService contains some operations which are required for all of our Wcf Services.

When Both DataFetchService and DataStorageService is hosted on same server, we get System.ArgumentException: 'An item with the same
key has already been added' exception when second service is added to the server. 
The problem arises due to the fact that each operation is getting identified by interface name and operation name, and because of it, it
shows that the operation is already added.

**Describe the solution you'd like**

Possible Solution:

We can add an optional parameter, for example a unique identifier string to the operations(method name) apart from interface name. This will allow us to add unique identifier while registering services to server and also while creating a client.

While generating Contract Description, append unique identifier string to service name in AnalyzeServiceAndinterfaces method and for properties ClientClassName, ContractClassName, ClientBuilder Class Name and EndpointClassName in Contract Description Class.

This solution will result in modifying CreateClient in following way: 
public IContract CreateClient<TContract>(ChannelBase channel, string uniqueIdentifierString="") in ClientFactory

Example:
```csharp
var client1 = clientFactory.CreateClient<IBootService>(channel,"DatafetchServiceUniqueString");
var client2 = clientFactory.CreateClient<IBootService>(channel, "DataStorageServiceUniqueString");
```
And for Server Service Registration in following way:
```csharp
public static Server.ServiceDefinitionCollection AddServiceModelSingleton<TService>(this Server,
 ServiceDefinitionCollection services, TService service, Action<ServiceModelGrpcServiceOptions>? configure=default,
 string uniqueIdentifierString="")
```
 in ServiceDefinitionCollectionExtensions

Example:
```csharp
server.Services.AddServiceModelSingleton(new DataFetchService(),null,"DataFetchServiceUniqueString"); 
server Services.AddServiceModelSingleton(new DataStorageService(),null,"DataStorageServiceUniqueString");
```
**Describe alternatives you've considered**
Alternatives we have considered are:
- Do not decorate IBootService with [ServiceContract] and just with [OperationContracts] like how you described [here](https://github.com/max-ieremenko/ServiceModel.Grpc/issues/70). But we cannot use this, because we would like to get client for all of the services running using IBootService Interface to manage lifecycles of those servers.
- Another alternative is to create a new server for each of the service implementation. But, this will require us to use too many ports as in my use case I have dozens of services. We would like  to avoid doing that.

**Comment by max-ieremenko** [comment]
It is [interface inheritance](https://max-ieremenko.github.io/ServiceModel.Grpc/ServiceAndOperationBinding.html). 

``` c#
public interface IBootService {}

[ServiceContract] 
public interface IDataFetchService : IBootService {}

[ServiceContract] 
public interface IDataStorageService : IBootService {}
```

> we would like to get client for all of the services running using IBootService Interface to manage lifecycles of those servers.

``` c#
var services = new ServiceCollection();

services.AddTransient<IDataFetchService>(_ => clientFactory.CreateClient<IDataFetchService>());
services.AddTransient<IDataStorageService>(_ => clientFactory.CreateClient<IDataStorageService>());

services.TryAddEnumerable(ServiceDescriptor.Transient<IBootService, IDataFetchService>(p => p.GetRequiredService<IDataFetchService>()));
services.TryAddEnumerable(ServiceDescriptor.Transient<IBootService, IDataStorageService>(p => p.GetRequiredService<IDataStorageService>()));

// allBoots: [IDataFetchService client,  IDataStorageService client]
var allBoots = services.BuildServiceProvider().GetServices<IBootService>();
```

**Comment by srdhruv** [comment]
I undertand the solution which you provided. But as I already mentioned it in alternatives we considered, that it would not be possible for us to implement. We cannot use interface inheritance in our solution.

There are some services which only implements IBootService.

For example:

```csharp
public class SomeClass1: IBootService
{
   ...
}

public class SomeClass2: IBootService
{
   ...
}
```
What we are actually trying to emulate is:

In WCF we can define custom endpoint address which lets us host mulitple instances of a Service Contract. For Example if I host SomeClass1 and SomeClass2 on same server, they could be hosted by specifying different endpoint address. 
```csharp
endpointAddress1 = "http://localhost:20250/SomeClass1/IBootservice";
endpointAddress2 = "http://localhost:20250/SomeClass2/IBootservice";
```
We will be able to emulate the above Functionality if we are able to specify unique identifier string while registering service.

**Comment by max-ieremenko** [comment]
In your example, there are two different services `SomeClass1` and `SomeClass2`, and they perform other tasks.
On the server side it is explicitly declared - ((IBootService)SomeClass1).Operation() != ((IBootService)SomeClass2).Operation().

Could you make the same explicit declaration to your client? The client also should be able to distinguish between (IBootService)SomeClass1 and (IBootService)SomeClass2:

``` c#
[ServiceContract]
public interface ISomeClass1 : IBootService {}

public class SomeClass1: ISomeClass1 {}

[ServiceContract]
public interface ISomeClass2 : IBootService {}

public class SomeClass2: ISomeClass2 {}
```

This is what I call "interface inheritance". In the code, both can be cast to IBootService, but at runtime may have different configurations, filters, interceptors, etc.

**Comment by srdhruv** [comment]
Thank you for suggesting this solution, we appreciate your input but we cannot use the solution which you are suggesting. The use cases which I explained earlier used class inheritance also. Instead of IBootService, we use a class named BootService which implements IBootService.

If we use Interface Inheritance, then wherever we are inheriting from IBootService, there will be code duplication.

I will try to give a more clear example below.

```csharp

[ServiceContract()]

public interface IBaseService
{
    [OperationContract()] 
    void InitializeRemoteService();
    
    [OperationContract()]
    void UninitializeRemoteService();

}

public class BaseService: IBaseService
{

  public void InitializeRemoteService()
  {
      // Code for InitializeRemoteService
  }
  
  public void UninitializeRemoteService()
  {
    // Code for UninitializeRemoteService
  }

} 

[ServiceContract()] 
public interface Foo
{
    [OperationContract()] 
    void DoFoo();
}

[ServiceContract()] 
public interface Bar
{
  [OperationContract()] 
  void DoBar();
}


public class FooService: BaseService, IFoo
{
  public void DoFoo()
  {
      // Code for DoFoo
  }
}

public class BarService: BaseService, IBar
{
  public void DoBar()
  {
    // Code for DoBar
  }
}

```

If we use "Interface Inheritance" which you explained, we will have to use

```csharp

[ServiceContract()]
public interface IFoo: IBaseService { ... }

[ServiceContract()]
public interface IBar: IBaseService { ... }

public class FooService: IFoo
{
    // Foo Implementation 
    public void DoFoo()
    {
        // Code for DoFoo
    }

    // IBaseService Implementation
    public void InitializeRemoteService()
    {
        // Code for InitializeRemoteService
    }

    public void UninitializeRemoteService()
    {
        // Code for UninitializeRemoteService
    }

}
public class BarService: IBar
{
    // Bar Implementation 
    public void DoBar()
    {
      // Code for DoBar
    }

  
    // IBaseService Implementation
    
    public void InitializeRemoteService()
     {
        // Code for InitializeRemoteService
    }
    
    public void UninitializeRemoteService()
    {
      // Code for UninitializeRemoteService
    }
}
```
BaseService Logic is same for all service classes.

In case we have this use case dozenes of times, we will have to write duplicate code for each of them. Hence, I ask you to consider the solution of adding unique identifiers to services.
Also I should point out that, our requirement is to get clients of type IFoo, **IBaseService** for FooService and IBar, **IBaseService** for BarService.

**Comment by max-ieremenko** [comment]
> If we use Interface Inheritance, then wherever we are inheriting from IBootService, there will be code duplication.

Here is [Demo.zip](https://github.com/max-ieremenko/ServiceModel.Grpc/files/11153720/Demo.zip) based on your example.

``` c#
public class FooService: BaseService, IFoo {}

public class BarService: BaseService, IBar {}
```

**Comment by srdhruv** [comment]
Thanks max, for taking time to responding to my queries. It really helped a lot. After some consideration, we have decided to spend some more time on research on our end.  I will close this issue for now and get back to you if we face any other issue.
Once again, thank you so much for all that you do. Your contributions to open source world are invaluable and deeply appreciated.
