### ISSUE TITLE
CallContext model is generated on Swagger

### ISSUE THREAD

**Issue by dimamoment** [max-ieremenko/ServiceModel.Grpc#144]
**Describe the bug**
I've got a Grpc code fist metho:
`Task<CreateReply> Create(CreateServiceRequest serviceRequest, CallContext? context = default)`
That method is represented in swagger, however, the Call-Context is also generated, when I trigger that endpoint it returns a 500 error. I would like to know if it's possible to exclude the "CallContext" parameter from being generated in the Swagger page.

**Expected behavior**
The "CallContext" parameter should not be generated in the Swagger page, even though it's included in the gRPC code for the "Create" method. This is because the "CallContext" parameter is intended to be an optional parameter used internally by the gRPC server, and not exposed to external clients.

**Environment**
 - .net 6

**Comment by max-ieremenko** [comment]
Context parameters such as CallContext, CancellationToken, CallOptions are not included in the swagger doc.

[Here](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/Swagger) are NSwagSwagger.sln and SwashbuckleSwagger.sln. I cannot reproduce your case "CallContext in the Swagger page".

Could you please help me to reproduce it?

**Comment by dimamoment** [comment]
remark: I use that one
`public readonly struct CallContext
  : ValueType
in namespace ProtoBuf.Grpc`

**Comment by max-ieremenko** [comment]
Swagger implementation in ServiceModel.Grpc does not support Protobuf.Grpc hosting and Protobuf.Grpc.CallContext in the contracts declarations.
