### ISSUE TITLE
Protobuf-net and Error Handling

### ISSUE THREAD

**Issue by lchristille** [max-ieremenko/ServiceModel.Grpc#148]
**Describe the bug**
When using Exception Handling and Protobuf-net as serializer, the detail of the exception is not received by the IClientErrorHandler.

**To Reproduce**
1. Create a new server with a service that throws a custom exception.
```csharp
[ServiceContract]
public interface ITerminalHealth
{
    [OperationContract]
    Task<HealthReply> ExceptionTestAsync(HealthRequest request);
}

public class TerminalHealthGate : ITerminalHealth
{
    public Task<HealthReply> ExceptionTestAsync(HealthRequest request)
    {
        throw new CustomException("Custom Exception Test Async");
    }
}
```
2. Define a Protobuf-net contract CustomExceptionDetail
```csharp
[ProtoContract]
public class CustomExceptionDetail
{
    [ProtoMember(1)] public string? Message { get; set; }
    [ProtoMember(2)] public string MethodName { get; set; } = string.Empty;
    [ProtoMember(3)] public string ExceptionType { get; set; } = string.Empty;
    [ProtoMember(4)] public Exception? InnerException { get; set; }
    [ProtoMember(5)] public StatusCode Status { get; set; }
}
```
3. Create a class that implements IServerErrorHandler, creates a new CustomExceptionDetail and returns it in the Detail property of a new ServerFaultDetail.
```csharp
public class ExceptionGrpcServerHandler : IServerErrorHandler
{
    public ServerFaultDetail? ProvideFaultOrIgnore(ServerCallInterceptorContext context, Exception error)
    {
        if (error is not CustomException exception) return null;

        var detail = exception.ToCustomExceptionDetail(context);
        return new ServerFaultDetail { Detail = detail };
    }
```
4. Configure the server to use ProtobufMarshallerFactory.Default as DefaultMarshallerFactory and ExceptionGrpcServerHandler as DefaultErrorHandler
```csharp
 _builder.Services.AddSingleton<IServerErrorHandler>(_ =>
        {
            var collection = new ServerErrorHandlerCollection(new ExceptionGrpcServerHandler());
            return collection;
        });

        _builder.Services.AddServiceModelGrpc(options =>
        {
            options.DefaultMarshallerFactory = ProtobufMarshallerFactory.Default;
            options.DefaultErrorHandlerFactory =
                serviceProvider => serviceProvider.GetRequiredService<IServerErrorHandler>();
        });
```
5 Create a class that implements IClientErrorHandler
```csharp
public class ExceptionGrpcClientHandler : IClientErrorHandler
{
    public void ThrowOrIgnore(ClientCallInterceptorContext context, ClientFaultDetail detail)
    {
        if (detail.Detail is CustomExceptionDetail customExceptionDetail)
        {
            // ....
        }
        else
        {
            throw new Exception(detail.OriginalError.Status.Detail);
        }
    }
}
```
6. Create a client for the Service created before from a factory with the corresponding configurations of the server and call the method
```csharp
    ClientFactory _defaultClientFactory = new(new ServiceModelGrpcClientOptions
    {
        MarshallerFactory = ProtobufMarshallerFactory.Default,
        ErrorHandler = new ClientErrorHandlerCollection(new ExceptionGrpcClientHandler())
    });

       var terminalHealthChannel = GrpcChannel.ForAddress("http://localhost:5003");
        var terminalHealthClient = __defaultClientFactory.CreateClient<ITerminalHealth>(terminalHealthChannel );
        try
        {
            await terminalHealthClient.ExceptionTestAsync(new HealthRequest());
        } catch (CustomException ex) {
         // ......
        }
```

**Expected behavior**
detail.Detail in ThrowOrIgnore method of ExceptionGrpcClientHandler contains the object passed to the ServerFaultDetail Detail property. Instead it is null, as if the object could not be deserialized.

**Environment**
 - OS: Windows 11
 - .net 7.0
 - ServiceModel.Grpc version 1.5.1

**Additional context**
With the same configuration, the system works as execpted if the ProtobufMarshallerFactory is removed from server and client configuration and annotations on the CustomExceptionDetail class are changed to [DataContract] and [DataMember(Order = x)]

**Comment by max-ieremenko** [comment]
```csharp
[ProtoContract]
public class CustomExceptionDetail
{
...
    // most probably the problem is here
    [ProtoMember(4)] public Exception? InnerException { get; set; }
...
}
```

Please test ProtoBuf serialization of your CustomExceptionDetail

```csharp
ProtoBuf.Meta.RuntimeTypeModel.Default.Serialize(
	Stream.Null,
	new CustomExceptionDetail
	{
		InnerException = new CustomException("Custom Exception Test Async")
	});
```

`
System.InvalidOperationException
  HResult=0x80131509
  Message=No serializer defined for type: System.Exception
  Source=protobuf-net.Core
  StackTrace:
   at ProtoBuf.Internal.ThrowHelper.NoSerializerDefined(Type type) in /_/src/protobuf-net.Core/Internal/ThrowHelper.cs:line 73
   at ProtoBuf.Meta.ValueMember.BuildSerializer() in /_/src/protobuf-net/Meta/ValueMember.cs:line 497
   at ProtoBuf.Meta.ValueMember.get_Serializer() in /_/src/protobuf-net/Meta/ValueMember.cs:line 229
`

**Comment by max-ieremenko** [comment]
> Sadly, in this situation no exception is thrown and there is no error in the console.

improved in version 1.5.2, see #153
