### ISSUE TITLE
[Question] What is the namespace for creation of a Channel?

### ISSUE THREAD

**Issue by alphajoza** [max-ieremenko/ServiceModel.Grpc#149]
In your readme page, you gave an example of how to create a Channel:
```
// create a channel
var channel = new Channel("localhost", 5000, ...);
```

I cannot create this `Channel` object because the closes one (which is suggested by Visual Studio) is from `System.Threading.Channels` which obviously that cannot be because `Channel` class in that namespace is static.

**Comment by max-ieremenko** [comment]
The ClientFactory accepts Grpc.Core.ChannelBase

```c#
ServiceModel.Grpc.Client.ClientFactory.CreateClient<TContract>(ChannelBase channel)
```

On the readme page, the code snippet is related to Grpc.Core.Channel from [Grpc.Core](https://www.nuget.org/packages/Grpc.Core), see [basic example](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/Basic)

```c#
// add a reference to Grpc.Core Nuget package in the .csproj

using Grpc.Core;

Grpc.Core.ChannelBase channel = new Grpc.Core.Channel("localhost", 5001, ChannelCredentials.Insecure);

ClientFactory.CreateClient<TContract>(channel);
```

also there is Grpc.Net.Client.GrpcChannel from [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client), see [grpc-dotnet-Counter example](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/grpc-dotnet-Counter)

```c#
// add a reference to Grpc.Net.Client Nuget package in the .csproj

using Grpc.Net.Client;

Grpc.Core.ChannelBase channel = Grpc.Net.Client.GrpcChannel.ForAddress("http://localhost:5000");

ClientFactory.CreateClient<TContract>(channel);
```

**Comment by alphajoza** [comment]
Yeah, I didn't pay attention to the `Examples` folder; really thorough and complete!

Just got it up and running.

Thanks.
