### ISSUE TITLE
Throwing an exception on the server side does not work properly on the Blazor WebAssembly client side

### ISSUE THREAD

**Issue by alphajoza** [max-ieremenko/ServiceModel.Grpc#151]
.net 7.0

server side: asp.net core
client side: blazor webAssembly

The grpc communication between server and client is working properly but when I'm trying to raise an error on the client from server (based on [here](https://max-ieremenko.github.io/ServiceModel.Grpc/global-error-handling.html) and [here](https://max-ieremenko.github.io/ServiceModel.Grpc/error-handling-general.html)), by for example throwing: `throw new ApplicationException("application error occur");` on the server side, what client side always gets is the following error:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="Cancelled", Detail="No grpc-status found on response. If the gRPC call is cross domain then CORS must be correctly configured. Access-Control-Expose-Headers needs to include 'grpc-status' and 'grpc-message'.")
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="No grpc-status found on response. If the gRPC call is cross domain then CORS must be correctly configured. Access-Control-Expose-Headers needs to include 'grpc-status' and 'grpc-message'.")
```

The message is mentioning CORS but I have configured it on the server side and have no problem for normal method invocation:
```
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAllOrigins", policyBuilder =>
    {
        policyBuilder.AllowAnyOrigin();
        policyBuilder.AllowAnyMethod();
        policyBuilder.AllowAnyHeader();
    });
});

app.UseCors("AllowAllOrigins");
```

**Comment by alphajoza** [comment]
Just got solved by exposing the required headers in the error message; the CORS configuration on the server side is now:

```
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAllOrigins", policyBuilder =>
    {
        policyBuilder.AllowAnyOrigin();
        policyBuilder.AllowAnyMethod();
        policyBuilder.AllowAnyHeader();
        policyBuilder.WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
    });
});
```

Just as a suggestion, it would be really helpful to mention such details in your examples with regard to usage of your awesome library in blazor wasm.

**Comment by max-ieremenko** [comment]
> Just as a suggestion, it would be really helpful to mention such details in your examples ...

see [Examples/BlazorApp/Server/Startup.cs](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/master/Examples/BlazorApp/Server/Startup.cs)
