### ISSUE TITLE
how to Initialize IClientBuilder?

### ISSUE THREAD

**Issue by hanxinimm** [max-ieremenko/ServiceModel.Grpc#167]
in the old nuget package 
i can use this code
![image](https://github.com/max-ieremenko/ServiceModel.Grpc/assets/13499426/4e5d2e8d-b628-49b8-b2da-e811c766de89)
to get  IClientBuilder<TContract>
but now, 
![image](https://github.com/max-ieremenko/ServiceModel.Grpc/assets/13499426/4b2b4965-d7c9-4da2-b375-d424bdb4a0de)

**Comment by max-ieremenko** [comment]
ServiceModel.Grpc.Client.**Internal.IClientBuilder** is the internal interface and should not be used directly from your code.

``` c#
namespace ServiceModel.Grpc.Client.Internal;

// This API supports ServiceModel.Grpc infrastructure and is not intended to be used directly from your code.
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public interface IClientBuilder<TContract>
```

For creating client instances from your code, please use ClientFactory, see [docs](https://max-ieremenko.github.io/ServiceModel.Grpc/ClientConfiguration.html) and [examples](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples).

``` c#
IClientFactory clientFactory = new ClientFactory(new ServiceModelGrpcClientOptions {...});
var client = clientFactory.CreateClient<TContract>(...);
```

**Comment by max-ieremenko** [comment]
I am closing this issue. If this is in error, let me know with a comment.
