### ISSUE TITLE
ServiceModel.WebApi

### ISSUE THREAD

**Issue by mircotamburini** [max-ieremenko/ServiceModel.Grpc#17]
like contract-first for gRPC.... can be interesting for WebApi Http

**Comment by max-ieremenko** [comment]
hello @mircotamburini,

i what about [Swagger/OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-5.0)?

**Comment by max-ieremenko** [comment]
hi @mircotamburini,

UP

**Comment by max-ieremenko** [comment]
Since the original poster hasn`t yet responded to the question made to them month ago, I am closing this issue.
I assume that the user has lost interest or resolved the problem on their own.
If this in error, let me know with a comment and I will be happy to reopen the issue.

**Comment by max-ieremenko** [comment]
Since the original poster hasn`t yet responded to the question made to them month ago, I am closing this issue.
I assume that the user has lost interest or resolved the problem on their own.
If this in error, let me know with a comment and I will be happy to reopen the issue.
