### ISSUE TITLE
Call GRPC hosted with Blazor (Asp.Net Core Server) from Console App 

### ISSUE THREAD

**Issue by aherrick** [max-ieremenko/ServiceModel.Grpc#179]
I am using the Blazor Example provided to host a GRPC Service. That works great.

I'm trying to also then call it the Service from a console app.

```
using Data.Shared.Services;
using Grpc.Core;
using ServiceModel.Grpc.Client;

await Task.Delay(10000);

var channel = new Channel("localhost", 7025, ChannelCredentials.Insecure);

// create a client factory
var clientFactory = new ClientFactory();

var chat = clientFactory.CreateClient<IChatService>(channel);

chat.Chat(new ChatDto()
{
    Query = "test"
});

Console.WriteLine("Shutting down");
Console.WriteLine("Press any key to exit...");
Console.ReadKey();
```

I get the following error:

`Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1703697824.513000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1703697824.513000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")'`

**Comment by max-ieremenko** [comment]
The exception "failed to connect to all addresses" is expected.

Blazor client in the Blazor example communicates with the server via HTTP 1.1.

In your code Grpc.Core.Channel can only communicate via HTTP 2.0.
Blazor server is configured only for HTTP 1.1, see Kestrel/Endpoints section in [appsettings.json](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/dd3f9dcb4b2eb2da85bc173741340f7da948ef61/Examples/BlazorApp/Server/appsettings.json#L11):

``` json
"Endpoints": {
  "default": {
    "Url": "http://*:5000",
    "Protocols": "Http1"
  }
}
``` 

To make your code work you need to add Http2 endpoint for Blazor server, for example, appsettings.json may look like this

``` json
"Endpoints": {
  "default": {
    "Url": "http://*:5000",
    "Protocols": "Http1"
  },
  "http2": {
    "Url": "http://*:5001",
    "Protocols": "Http2"
  }
}
```
in your code connect to HTTP 2.0 on port 5001

```csharp
var channel = new Channel("localhost", 5001, ChannelCredentials.Insecure);
```
You can just run your code.

---------------------------------------------------------------------
Another variant is to use HTTP 1.1 connection as Blazor client does:

```xml
<ItemGroup>
  <PackageReference Include="Grpc.Net.Client" />
  <PackageReference Include="Grpc.Net.Client.Web" />
</ItemGroup>
```

connect to HTTP 1.1 on port 5000
```csharp
var httpHandler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());
httpHandler.HttpVersion = System.Net.HttpVersion.Version11;

var channel = GrpcChannel.ForAddress("http://localhost:5000", new GrpcChannelOptions { HttpHandler = httpHandler });

var client = new ClientFactory().CreateClient<IWeatherForecastService>(channel);
```

**Comment by aherrick** [comment]
Thank you for the detailed answer! closing :)

**Comment by aherrick** [comment]
Also realized you can do 'Http1AndHttp2' to target both on the same port correct
