### ISSUE TITLE
Null Headers in CallOptions when using DefaultCallOptionsFactory

### ISSUE THREAD

**Issue by jeffdoolittle** [max-ieremenko/ServiceModel.Grpc#20]
I have tried using the following clientOptions both by passing them to `ClientFactory` and by passing them in to the generated client extensions (using the DesignTime capabilities)

```csharp
var clientOptions = new ServiceModelGrpcClientOptions
{
    DefaultCallOptionsFactory = () =>
        new CallOptions(new Metadata(), DateTime.UtcNow.Add(delay), cts.Token)
};
```
The generated code looks like this:

```csharp
Task<bool> Arpc.Tests.IMembershipManager.SubmitApplication(Arpc.Tests.ApplyForMembership value, Guid correlationId, CancellationToken cancellationToken)
{
    var __callOptions = new CallOptionsBuilder(DefaultCallOptionsFactory)
        .WithCancellationToken(cancellationToken)
        .Build();
    var __request = new Message<Arpc.Tests.ApplyForMembership, Guid>(value, correlationId);
    var __call = CallInvoker.AsyncUnaryCall(Contract.MethodSubmitApplication, null, __callOptions, __request);
    var __response = ClientChannelAdapter.GetAsyncUnaryCallResult(__call, null, __callOptions.CancellationToken);
    return __response;
}
```

The `CallOptionsBuilder` calls `DefaultCallOptionsFactory` and receives a new `CallOptions` built by the `DefaultCallOptionsFactory` configured on `clientOptions` above.

However, `__callOptions` has a `null` value for `Headers`!

![Screen Shot 2021-01-20 at 9 35 00 AM](https://user-images.githubusercontent.com/105651/105212872-d9f97a80-5b02-11eb-91e2-3a4c3698da99.png)

I am running net5 on MacOS.

**Comment by max-ieremenko** [comment]
hello @jeffdoolittle,

for gRPC framework _new CallOptions(headers: null)_ and _new CallOptions(headers: new Metadata())_ are identical - no request headers.

In this example __callOptions will contain non-null Headers:
``` c#
var clientOptions = new ServiceModelGrpcClientOptions
{
    DefaultCallOptionsFactory = () =>
        new CallOptions(new Metadata { { "some-header", "some value" } }, DateTime.UtcNow.Add(delay))
};
```
also CancellationToken in DefaultCallOptionsFactory is redundant: SubmitApplication(ApplyForMembership, Guid, _CancellationToken_).

**Comment by max-ieremenko** [comment]
Hi @jeffdoolittle,

as i see my comment did not help at all.
Could you please give me a bigger picture of what you need to implement?

**Comment by max-ieremenko** [comment]
Since the original poster hasn`t yet responded to the question made to them one month ago, I am closing this issue.
I assume that the user has lost interest or resolved the problem on their own.
If this in error, let me know with a comment and I will be happy to reopen the issue.
