### ISSUE TITLE
(Question|Feature request): gRPC server reflection

### ISSUE THREAD

**Issue by ikopytko** [max-ieremenko/ServiceModel.Grpc#219]
I haven't found any discussion or references in code about gRPC reflection feature. To give a context - it is possible to enable reflection on both [Grpc.AspNetCore](https://learn.microsoft.com/en-us/aspnet/core/grpc/test-tools?view=aspnetcore-8.0#set-up-grpc-reflection) and [protobuf-net.Grpc](https://martinbjorkstrom.com/posts/2020-07-08-grpc-reflection-in-net), which will add service discovery feature which can be used in different clients like Postman, grpcurl, grpc-cli, etc. This is slightly more useful than swagger in some cases. I don't know if this is a matter of correct configuration or it will require an implementation as ServiceModel feature.

**Comment by max-ieremenko** [comment]
> ServiceModel.Grpc enables applications to communicate with gRPC services using a code-first approach (no .proto files), helps to get around limitations of gRPC protocol like "only reference types", "exact one input", "no nulls", "no value-types"

gRPC reflection is not supported.

**Comment by ikopytko** [comment]
Check out, please, second link. There is an example of reflection together with code first server using protobuf-net. Thought this may be similar to what ServiceModel can do.

P.S. Appreciate for the quick response.

**Comment by max-ieremenko** [comment]
protobuf-net.Grpc is a serializer compatible with Google Protobuf.
With `ServiceModel.Grpc` you are not limited to Google Protobuf, using any other serializer by design does not support gRPC reflection.

**Comment by ikopytko** [comment]
I see, now I'm curious if it is possible to implement for Protobuf Marshaller. 
protobuf-net creates service descriptor dynamically in [schema generator](https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/src/protobuf-net.Grpc.Reflection/SchemaGenerator.cs#L46), smth like reverse engineering .proto files from C# contracts and services. 
But this might be outside of this question.
Thanks
