### ISSUE TITLE
Any plan for grpc-dotnet?

### ISSUE THREAD

**Issue by vuong17021** [max-ieremenko/ServiceModel.Grpc#22]
Do you have any plan for grpc-dotnet?

**Comment by max-ieremenko** [comment]
Hi @vuong1702,

not sure i understand your question.

If you are asking about support for grpc-dotnet in ServiceModel.Grpc, this is out of the box: see [Counter](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/grpc-dotnet-Counter) and [Compressor](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/grpc-dotnet-Compressor) examples.
Is this what you are looking for?

**Comment by vuong1702** [comment]
> Hi @vuong1702,
> 
> not sure i understand your question.
> 
> If you are asking about support for grpc-dotnet in ServiceModel.Grpc, this is out of the box: see [Counter](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/grpc-dotnet-Counter) and [Compressor](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/grpc-dotnet-Compressor) examples.
> Is this what you are looking for?

grpc-dotnet with .net 5 has many features and I'm a web developer so the most important to me is performance. Do you have any plan to migrate this project to grpc-dotnet.
