### ISSUE TITLE
How to implement a client interceptor with AddServiceModelGrpcClientFactory

### ISSUE THREAD

**Issue by pljAtEwe** [max-ieremenko/ServiceModel.Grpc#234]
Hi,
I am trying to add a client interceptor that should apply to all clients for adding current user info to the header of all outgoing grpc call.

I am using ClientServiceCollectionExtensions.AddServiceModelGrpcClientFactory followed by call to IClientFactoryBuilder.AddClient for creating the client factory but I cannot find a way to add the client interceptors to the created clients similar to how it is possible to call GrpcHttpClientBuilderExtensions.AddInterceptor() when clients are created using the IHttpClientBuilder.

**Comment by max-ieremenko** [comment]
Hi @pljAtEwe,

If it is only client`s HTTP header(s), please adapt a little bit [Examples/ClientDependencyInjection/Client.ReflectionEmit/DemoGrpcNetClientFactory.cs](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/00bce042c6d8096cfce0e34671e7774fce94b279/Examples/ClientDependencyInjection/Client.ReflectionEmit/DemoGrpcNetClientFactory.cs#L13)

```c#
IServiceCollection services = ...

services
    .AddServiceModelGrpcClientFactory((factoryOptions, provider) =>
    {
        factoryOptions.DefaultCallOptionsFactory = () =>
        {
            var headers = new Metadata
            {
                { "YourHeaderName-1", "HeaderValue-1" },
                ...
                { "YourHeaderName-n", "HeaderValue-n" }
            };
            return new CallOptions(headers);
        };
    });
```

it is similar to the example [Examples/JsonWebTokenAuthentication/Client/Services/CallOptionsFactoryWithAuthorization.cs](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/00bce042c6d8096cfce0e34671e7774fce94b279/Examples/JsonWebTokenAuthentication/Client/Services/CallOptionsFactoryWithAuthorization.cs)

**Comment by pljAtEwe** [comment]
Thanks for quick answer - exactly what I needed :-)

**Comment by pljAtEwe** [comment]
Another related question: 
when using ClientServiceCollectionExtensions.AddServiceModelGrpcClientFactory followed by call to IClientFactoryBuilder.AddClient for creating the client factory I cannot find a way to configure httpClient.Timeout value ?

**Comment by max-ieremenko** [comment]
https://github.com/max-ieremenko/ServiceModel.Grpc/blob/3a32ac642056432ab314f91fdb9af0d1834dcd86/Examples/ClientDependencyInjection/Client.DesignTime/DemoGrpcNetChannel.cs#L60
