### ISSUE TITLE
method overloading doesn't work on Swagger

### ISSUE THREAD

**Issue by EunjeongChoi414** [max-ieremenko/ServiceModel.Grpc#258]
### Problem 
```csharp
[ServiceContract]
public interface ITestRpc
{
  [OperationContract]
  public Task TestAsync(string abc); 

  [OperationContract]
  public Task TestAsync(string abc, string def); 
}
```
and this case 
```csharp
interface A
{
    int add();
}


interface B
{
    int add();
}
```
I thought method overloading will work and made two APIs like above but I found out that they don't appear in Swagger. 

### Question
1. Is this an expected outcome?
2. Is there any way I can see my methods on Swagger.

**Comment by max-ieremenko** [comment]
There is a naming conflict in your contract definition.

Please read [ServiceModel.Grpc service and operation names](https://max-ieremenko.github.io/ServiceModel.Grpc/ServiceAndOperationName.html) and [service and operation bindings](https://max-ieremenko.github.io/ServiceModel.Grpc/ServiceAndOperationBinding.html)

**Comment by EunjeongChoi414** [comment]
> There is a naming conflict in your contract definition.
> 
> Please read [ServiceModel.Grpc service and operation names](https://max-ieremenko.github.io/ServiceModel.Grpc/ServiceAndOperationName.html) and [service and operation bindings](https://max-ieremenko.github.io/ServiceModel.Grpc/ServiceAndOperationBinding.html)

Thank you for the quick response. I saw the documents but it seems like there's no data contract names. 
Is there any way I can avoid the naming issue when the two data contracts' names are the same like the below. 

```csharp
namespace Standard
{
    [ServiceContract(Name = "Standard.Calculator")]
    public interface ICalculator { 

     [DataContract]
     public record Param(int a);

     }
}

namespace Scientific
{
    [ServiceContract(Name = "Scientific.Calculator")]
    public interface ICalculator { 

    [DataContract]
     public record Param(int a);

    }
}
```
