### ISSUE TITLE
Swagger 'The same schemaId is already used' exception occur

### ISSUE THREAD

**Issue by EunjeongChoi414** [max-ieremenko/ServiceModel.Grpc#259]
**Describe the bug**
```csharp
public record Param
{
    string Abc; 
}

interface A 
{
    public Task TestAsync(Param param, CancellationToken cancel = default); 

    public record Param
    {
       string Abc; 
       bool Def; 
    }
}
```
Above two Param classes should be considered different classes but when Param is used in the rpc API Swagger throws this exception. 
``` text
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type...
The same schemaId is already used for type...
```

**To Reproduce**
Make record classes inside and outside of the rpc interface and use the one inside the interface as the parameter of a rpc. 

**Expected behavior**
The error shouldn't occur. 

**Environment**
 - .net framework version 8.0

**Comment by max-ieremenko** [comment]
The described case does not apply to the code in this repository.

**To Reproduce**

- follow [Get started with Swashbuckle and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio) to create a simple project
- create action(s) to use both models `Param` and `A.Param`
- try to generate swagger.json

```
... The same schemaId is already used for type ...
```

There is nothing to do in ServiceModel.Grpc Swagger integration.
