### ISSUE TITLE
server streaming with external data gives exception. 

### ISSUE THREAD

**Issue by EunjeongChoi414** [max-ieremenko/ServiceModel.Grpc#260]
**Describe the bug**
I need to return one IAsyncEnumerable<T> and one boolean type in my api. The [docs](https://max-ieremenko.github.io/ServiceModel.Grpc/operation-server-streaming.html#:~:text=ServiceModel.Grpc%20framework%20supports%20external%20data%20in%20the%20response) says it works but below didn't work in my environment. 

```csharp
    [OperationContract]
    public Task<(bool param1, IAsyncEnumerable<int> param2)> Test();
```

gives this error.  
```
 System.InvalidOperationException : Fail to resolve header parameters, smgrpc-method-output-bin header not found.
```

**To Reproduce**
return one IAsyncEnumerable<TData> with one boolean type. 

**Expected behavior**
no exception occurs

**Environment**
 - OS: [e.g. Windows/Linux and version] macOS 15.0.1
 - .net framework version 8.0

**Additional context**

**Comment by max-ieremenko** [comment]
I cannot reproduce the issue:

- use [Examples/Basic](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/Basic)
- extend [IPersonService](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/115a5c8c1f925f40561fd648e1d6b26f1608644d/Examples/Basic/Contract/IPersonService.cs#L38) with `Task<(bool param1, IAsyncEnumerable<int> param2)> Test();`
- extend [ClientCalls](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/master/Examples/Basic/Client/ClientCalls.cs)

It works.
