### ISSUE TITLE
Question, Json web http APIs

### ISSUE THREAD

**Issue by igalHcsra** [max-ieremenko/ServiceModel.Grpc#34]
Hi Max, love this package!

I'm currently trying to generate some UI documentation for each microservice.
I found some progression by microsoft to support grpc ui with some pre-release nuget packages.

Is there a way the service model approach can support swagger with this article's instructions?
https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0

I guess there is a problem this the fact there is no protobuf file to place the `option (google.api.http)` method.

Anyway the swagger library responses me  with:
`warn: Microsoft.AspNetCore.Grpc.HttpApi.HttpApiServiceMethodProvider[1]
      Could not find bind method for ServiceModelName1Service.`

`warn: Microsoft.AspNetCore.Grpc.HttpApi.HttpApiServiceMethodProvider[1]
      Could not find bind method for ServiceModelName2Service.`

So it's clear a sign that the library recognizes the gRPC mappings which are native to `dotnet-grpc` .
Is there a way to support it with code first approach built by your library with this information?

**Comment by max-ieremenko** [comment]
Hi igalHcsra,

Thank you for request. I put your topic in my todo list.

What I can see right away is a possible limitation to only unary methods and POST. In any case requires some research.

**Comment by max-ieremenko** [comment]
Hi igalHcsra,

I have no plans to integrate ServiceModel.Grpc with Microsoft.AspNetCore.Grpc.HttpApi: HttpApi is in alpha state.

I like the idea about swagger support, there for ServiceModel.Grpc.AspNetCore.Swashbuckle is released in version 1.2.0.
Integration is in a pre-release state.
Please check this example [SwashbuckleSwaggerIntegration](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/SwashbuckleSwaggerIntegration). 

Your feedback is appreciated.

**Comment by igalHcsra** [comment]
Hi Max,
Works great!
Thank you very much for everything, I see you really put the effort in that one.
Can I somehow get the swagger request "Try it out" method to work with JsonElement?
JsonElement is a crucial feature in swagger for dynamic objects to be serialized, in the current swagger implementation it is not being serialized.

**Comment by max-ieremenko** [comment]
Hi igalHcsra,

i have doubts that i understand your question about JsonElement.  Do you ask about contract like this?
``` c#
[ServiceContract]
public interface ITestService
{
    [OperationContract]
    Task<JsonElement> Ping(JsonElement element1, JsonElement element2);
}
```

**Comment by igalHcsra** [comment]
````cs    
[DataContract]
    public class TestContract
    {
        [DataMember]
        public JsonElement TestDynamicData { get; set; }
    }
````

**Comment by max-ieremenko** [comment]
Behind the scenes http request from swagger UI is converted into standard gRPC request by ServiceModel.Grpc HTTP/1.1 JSON gateway.
Before "Try it out" from swagger UI, please make sure that standard gRPC communication is working.

I assume you already have the following service implementation:

``` c#
[DataContract]
public class TestContract
{
    [DataMember]
    public JsonElement TestDynamicData { get; set; }
}

[ServiceContract]
public interface ITestService
{
    [OperationContract]
    Task<TestContract> Ping(TestContract contract);
}

public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddServiceModelGrpc(options => 
		{
			// here should be marshaller factory, which can correctly serialize and deserialize instance of TestContract
			options.DefaultMarshallerFactory = new ...
		});
	}
}
```

Test gRPC client call, example can be found [here](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/Basic)

``` c#
var clientFactory = new ClientFactory
{
	// here should be marshaller factory, which can correctly serialize and deserialize instance of TestContract, the same as in Startup.cs on server 
	MarshallerFactory = new ...
};

var channel = new Channel("localhost", 5000, ...);
var proxy = clientFactory.CreateClient<ITestService>(channel);

var contract = new TestContract
{
	TestDynamicData = ... // set JsonElement
};
await proxy.Ping(contract);
```

when `proxy.Ping(contract)` works then you can use swagger UI "Try it out" with following JSON:
``` c#
{
	"contract": {
		"testDynamicData": {
			"property1": 1,
			"property2": "some text"
		}
	}
}
```

JsonElement in the TestContract can be correctly handled by System.Text.Json.JsonSerializer.
ServiceModel.Grpc does not provide MarshallerFactory based on System.Text.Json.JsonSerializer.

The following implementation can be used:

``` c#
public sealed class JsonMarshallerFactory : IMarshallerFactory
{
	public Marshaller<T> CreateMarshaller<T>()
	{
		return new Marshaller<T>(Serialize, Deserialize<T>);
	}

	private static void Serialize<T>(T value, SerializationContext context)
	{
		using (var buffer = context.AsStream())
		using (var writer = new Utf8JsonWriter(buffer))
		{
			JsonSerializer.Serialize(writer, value);
		}

		context.Complete();
	}

	private static T Deserialize<T>(DeserializationContext context)
	{
		var reader = new Utf8JsonReader(context.PayloadAsReadOnlySequence());
		return JsonSerializer.Deserialize<T>(ref reader)!;
	}
}
```

**Comment by igalHcsra** [comment]
The marshaller works great it really covers the swagger functionallity to the fullest, is there a way to use the marshaller for sending also 'object' or 'dynamic' types as well?
I think I'll make the serializer to differ when it comes from the swagger client or any other so when it's a swagger call it will use the jsonMarshaller and when it comes from c# client then use an 'object' type.

**Comment by max-ieremenko** [comment]
> is there a way to use the marshaller for sending also 'object' or 'dynamic' types as well?

As you can see it is fully under your control.

Swagger call is just an emulation of client call

Standard gRPC workflow for client call:

1. client call
2. marshaller.serialize() request
3. http call
4. marshaller.deserialize() request
5. invoke you service
6. marshaller.serialize() response
7. http response
8. marshaller.deserialize() response

Swagger UI call:

1. http request with json body
2. ServiceModel.Grpc HTTP/1.1 JSON gateway deserialize from json
3. ServiceModel.Grpc HTTP/1.1 JSON gateway make gRPC request
4. marshaller.serialize() request
5. invoke gRPC (the same as for client call)
6. marshaller.deserialize() request (the same as for client call)
5. invoke you service (the same as for client call)
6. marshaller.serialize() response (the same as for client call)
7. ServiceModel.Grpc HTTP/1.1 JSON gateway marshaller.deserialize() response
8. ServiceModel.Grpc HTTP/1.1 JSON gateway serialize response into json
9. return json to Swagger UI

**Comment by igalHcsra** [comment]
Brilliant! Thank you very much Max you are exellent!
