### ISSUE TITLE
Can Use FluentValidation For Validate Model ?

### ISSUE THREAD

**Issue by majidbigdeli** [max-ieremenko/ServiceModel.Grpc#44]
@max-ieremenko  Hello 

Can Use [FluentValidation ](https://docs.fluentvalidation.net/en/latest/aspnet.html) for Validate Model ?

What is your suggestion For Model Validation ?
For Example a Parameter Is Required  or check min length

**Comment by max-ieremenko** [comment]
**return exception**
By default it is RpcException, If you need more detailed exception, check [docs/error handling](https://github.com/max-ieremenko/ServiceModel.Grpc/blob/master/docs/global-error-handling.md)

**status code 400**
This is not supported by gRPC design: in any case (success or exception in your method/operation) gRPC returns 200 OK.
