### ISSUE TITLE
IEnumerable data is not empty array, it is null?

### ISSUE THREAD

**Issue by hanxinimm** [max-ieremenko/ServiceModel.Grpc#89]
i hava a method 
public Task<IEnumerable<TenantListResponse>> QueryTenantListAsync(int appId, long accountId)

return IEnumerable<TenantListResponse>

but when the array is [] ,it is return null? how to break it?

**Comment by max-ieremenko** [comment]
what kind of marshaller/dataserializer do you use?

**Comment by hanxinimm** [comment]
@max-ieremenko  ProtobufMarshallerFactory
![image](https://user-images.githubusercontent.com/13499426/169970263-74fb0496-7ed2-4bb5-acbf-d0dcee3c8a8f.png)

**Comment by hanxinimm** [comment]
@max-ieremenko   
i use MessagePackMarshallerFactory in  DesignTime code 
![image](https://user-images.githubusercontent.com/13499426/170012390-3495075e-025a-4807-a67b-cb970646fe5d.png)
![image](https://user-images.githubusercontent.com/13499426/170012417-75401cf3-a301-4bc3-9499-f10964c10705.png)

but it have other error

MessagePackSerializationException: Building dynamic formatter only allows public type. Type: Labor.Customer.ProxyFactory.Service.GrpcServices.GrpcArchiveQueryService+Message`6


i think it about the internal Message Definition

![image](https://user-images.githubusercontent.com/13499426/170012810-6cb1672a-17d0-4615-8665-0b1d98dddc4b.png)

how fix it?

**Comment by max-ieremenko** [comment]
> ImportGrpcService add a parameter MarshallerType, is default DataContract

- applying MessagePack attributes does not solve the issue "only allows public type"
- MessagePack recognizes DataContract attributes perfectly
- generated code must be marshaller independent

**Comment by max-ieremenko** [comment]
@hanxinimm 

Please try version 1.4.8, GrpcArchiveQueryService should work without any workarounds.

**Comment by max-ieremenko** [comment]
Since the original poster hasn`t yet responded to the request made to them month ago, I am closing this issue.
I assume that the user has lost interest or problem is resolved.
If this in error, let me know with a comment and I will be happy to reopen the issue.
